### ISSUE TITLE
bug: Yapsy gives errors about failed subclass tests

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Yapsy makes a lot of traceback errors when trying to initialize plugins (in this case Firefox Gnome Theme plugin):
```
[DEBUG] [yapsy] PluginFileLocator walks (recursively) into directory: /home/tfuxc/.local/share/gradience/plugins
[DEBUG] [yapsy] PluginFileLocator walks (recursively) into directory: /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins
[DEBUG] [yapsy] firefox_gnome_theme.py is not a valid plugin for strategy info_ext
[DEBUG] [yapsy] PluginFileLocator found a candidate:
    /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme.yapsy-plugin
[DEBUG] [yapsy] correct subclass tests failed for: Adw in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: BASE in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: Gtk in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __builtins__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __cached__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __doc__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __file__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __loader__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __name__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __package__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: __spec__ in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
[DEBUG] [yapsy] correct subclass tests failed for: os in /home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/builddir/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/home/tfuxc/Documents/MyStuff/Forks/AdwCustomizer/venv/lib/python3.10/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
TypeError: issubclass() arg 1 must be a class
```

### Expected behavior

It shouldn't give those errors on plugin init

### OS

Arch Linux

### Version

From main branch

### Installation method

Manual using meson

### Additional context

Use Devel builds to get errors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
I got the same but that seems to not causing any problems

**Comment by aspizu** [comment]
we could switch from yapsy to a homegrown plugin system

**Comment by 0xMRTT** [comment]
Yep, and package it in the lib

**Comment by 0xMRTT** [comment]
Or fork yaspy ?

**Comment by aspizu** [comment]
forking yaspy would just create more problems

**Comment by tfuxu** [comment]
This is still a relevant issue, so I'm reopening it.
