### ISSUE TITLE
bug: VanillaOS' read-only root system makes Gradience Nightly completely pointless

### ISSUE THREAD

**Issue by bulkabuka** [GradienceTeam/Gradience#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

VanillaOS comes with read-only system files, so the app cannot access stylesheets and color variables. Also there's a few exceptions when trying to apply theme. App is just showing the error shown below and doesn't actually apply any theme (Color variables doesn't load)

### To Reproduce

1. Install VanillaOS
2. Install & Open Gradience Nightly
3. Try to apply any theme or color choice

### Expected behavior

Theme applies and colors changing.

### Screenshots

![The error on startup](https://github.com/GradienceTeam/Gradience/assets/74786850/8dbf2bb2-8739-467d-804e-0fdd03f74ba3)

### OS

VanillaOS 22.10

### DE/WM version

GNOME 43.1

### Version

0.8.0-beta1-36b91fe

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

blur-my-shell@aunetx
clipboard-history@alexsaveau.dev
custom-accent-colors@demiskp
rounded-window-corners@yilozt
user-stylesheet@tomaszgasior.pl
noannoyance@daase.net
user-theme@gnome-shell-extensions.gcampax.github.com

### Additional context

Full console log:

```bash
sara@vanilla:~$ flatpak run com.github.GradienceTeam.Gradience.Devel
[yapsy] PluginFileLocator walks (recursively) into directory: /home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/data/gradience/plugins
[yapsy] PluginFileLocator walks (recursively) into directory: /app/share/gradience/plugins
[yapsy] firefox_gnome_theme.py is not a valid plugin for strategy info_ext
[yapsy] PluginFileLocator found a candidate:
    /app/share/gradience/plugins/firefox_gnome_theme.yapsy-plugin
[yapsy] mailspring.py is not a valid plugin for strategy info_ext
[yapsy] PluginFileLocator found a candidate:
    /app/share/gradience/plugins/mailspring.yapsy-plugin
[yapsy] qt5ct.py is not a valid plugin for strategy info_ext
[yapsy] PluginFileLocator found a candidate:
    /app/share/gradience/plugins/qt5ct.yapsy-plugin
[yapsy] correct subclass tests failed for: TEMPLATE in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __builtins__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __cached__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __doc__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __file__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __loader__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __name__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __package__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __spec__ in /app/share/gradience/plugins/firefox_gnome_theme
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: TEMPLATE in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __builtins__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __cached__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __doc__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __file__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __loader__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __name__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __package__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __spec__ in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: os in /app/share/gradience/plugins/mailspring
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __builtins__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __cached__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __doc__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __file__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __loader__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __name__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __package__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: __spec__ in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[yapsy] correct subclass tests failed for: os in /app/share/gradience/plugins/qt5ct
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/yapsy/PluginManager.py", line 535, in loadPlugins
    is_correct_subclass = issubclass(element, self.categories_interfaces[category_name])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
[Gradience] DEBUG: setup plugins
[Gradience] DEBUG: Loaded custom CSS variables: {'accent_color': '#ffbe6f', 'accent_bg_color': '#ff7800'}
[Gradience] DEBUG: <gradience.backend.models.preset.Preset object at 0x7fa163cb7b10>
[Gradience] ERROR: An unexpected error occurred while loading variable colors.
	Exc: 'window_bg_color'
	At: /app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py:89
	    /app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py:102
[Gradience] DEBUG: presets_dir.iterdir: /home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/config/presets/user
[Gradience] DEBUG: presets_dir.iterdir: /home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/config/presets/curated
[Gradience] DEBUG: presets_dir.iterdir: /home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/config/presets/official
[Gradience] DEBUG: normal run
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-shell', '--version']
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-extensions', 'list']
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-shell', '--version']
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-extensions', 'list', '--enabled']
[Gradience] DEBUG: Spawning: ['flatpak-spawn', '--host', 'gnome-shell', '--version']
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 138, in _apply_theme_thread
    output = self.apply_theme(source_object, theme_variant, preset)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 150, in apply_theme
    self._create_theme(parent, preset)
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 163, in _create_theme
    self._insert_variables()
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 192, in _insert_variables
    inserted = line.replace("{{" + _key + "}}", self.preset_palette[prefix][key])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: '1'
[Gradience] DEBUG: It works! \o/
[Gradience] ERROR: An unexpected error occurred while loading variable colors.
	Exc: 'window_bg_color'
	At: /app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py:89
	    /app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py:102
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/preset.py", line 121, in apply_preset
    with open(gtk_css_path + ".bak", "w", encoding="utf-8") as backup:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/config/gtk-4.0/gtk.css.bak'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/frontend/main.py", line 610, in apply_color_scheme
    PresetUtils().apply_preset("gtk4", self.preset)
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/preset.py", line 125, in apply_preset
    with open(gtk_css_path, "w", encoding="utf-8") as css_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/home/sara/.var/app/com.github.GradienceTeam.Gradience.Devel/config/gtk-4.0/gtk.css'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Hello, from what I can see with the traceback, this isn't related to Vanilla OS but to a misconfiguration. Indeed, you missed to configure flatpak override.

You can enable flatpak ovveride from Gradience Preferences
