### ISSUE TITLE
bug: Error when applying GTK-3 Theme.

### ISSUE THREAD

**Issue by aspizu** [GradienceTeam/Gradience#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Errors out, no css is output in `~/.config/gtk-3.0/`
```sh
(process:256003): Adwaita-WARNING **: 09:39:17.317: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/main.py", line 613, in apply_color_scheme
    PresetUtils().apply_preset("gtk3", self.preset)
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/preset.py", line 120, in apply_preset
    self.set_gtk3_theme()
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/preset.py", line 46, in set_gtk3_theme
    self.settings.set("gtk-theme", "adw-gtk3")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'GSettingsSetting' object has no attribute 'set'
```

### To Reproduce

1. Apply GTK-3 Theme

### Expected behavior

Theme should be applied.

### OS

Arch Linux

### DE/WM version

Hyprland

### Version

0.8.0-beta1

### Installation method

AUR

### Additional context

AUR Package `gradience-git`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Hmm, little bug when there's not system-wide ext
