### ISSUE TITLE
bug: Error when installing from aur (error: Could not determine what kind of syntax is meant here)

### ISSUE THREAD

**Issue by nikelborm** [GradienceTeam/Gradience#823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to install gradience-git on a clean system (removed python-argparse, cleared yay cache and removed python-material-color-utilities)

While building it thrown error: `Could not determine what kind of syntax is meant here`

### To Reproduce

1. install latest arch with yay
2. attempt to install gradience with `yay gradience-git` (usual gradience also does not work)

### Expected behavior

Gradience-git builds without error

### OS

Arch Linux x86_64

### DE/WM version

GNOME 44.4

### Version

AUR gradience-git 0.3.1.r2.ge5dd5c9-1 (latest in AUR)

### Installation method

AUR

### Additional context

Important logs from yay during installation
```
==> Starting build()...
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true -D python.bytecompile=1 Gradience build
The Meson build system
Version: 1.2.1
Source dir: /home/nikel/.cache/yay/gradience-git/src/Gradience
Build dir: /home/nikel/.cache/yay/gradience-git/src/build
Build type: native build
Project name: gradience
Project version: 0.8.0-beta1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency glib-2.0 found: YES 2.78.0
Run-time dependency gtk4 found: YES 4.12.1
Run-time dependency libadwaita-1 found: YES 1.3.5
Run-time dependency pygobject-3.0 found: YES 3.46.0
Run-time dependency libsoup-3.0 found: YES 3.4.2
Program python3 (lxml) found: YES (/usr/bin/python3) modules: lxml
Configuring constants.py using configuration
Configuring gradience using configuration
Configuring gradience-cli using configuration
Program blueprint-compiler found: YES (/usr/bin/blueprint-compiler)
Configuring com.github.GradienceTeam.Gradience.desktop.in using configuration
Program msgfmt found: YES (/usr/bin/msgfmt)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring com.github.GradienceTeam.Gradience.appdata.xml.in using configuration
Program appstream-util found: YES (/usr/bin/appstream-util)
Configuring com.github.GradienceTeam.Gradience.gschema.xml using configuration
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program msginit found: YES (/usr/bin/msginit)
Program msgmerge found: YES (/usr/bin/msgmerge)
Program xgettext found: YES (/usr/bin/xgettext)
Build-time dependency gio-2.0 found: YES 2.78.0
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Program gtk4-update-icon-cache found: YES (/usr/bin/gtk4-update-icon-cache)
Program update-desktop-database found: YES (/usr/bin/update-desktop-database)
Build targets in project: 29

gradience 0.8.0-beta1

  User defined options
    auto_features     : enabled
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    sbindir           : bin
    wrap_mode         : nodownload
    python.bytecompile: 1
    b_lto             : true
    b_pie             : true

Found ninja-1.11.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja                                                                                                                          
INFO: calculating backend command to run: /usr/bin/ninja -C /home/nikel/.cache/yay/gradience-git/src/build
ninja: Entering directory `/home/nikel/.cache/yay/gradience-git/src/build'
[25/26] Generating data/ui/blueprints with a custom command
FAILED: data/ui 
/usr/bin/blueprint-compiler batch-compile data/ui/. ../Gradience/data/ui ../Gradience/data/ui/error_list_row.blp ../Gradience/data/ui/palette_shades.blp ../Gradience/data/ui/option_row.blp ../Gradience/data/ui/window.blp ../Gradience/data/ui/monet_theming_group.blp ../Gradience/data/ui/app_type_dialog.blp ../Gradience/data/ui/custom_css_group.blp ../Gradience/data/ui/presets_manager_window.blp ../Gradience/data/ui/reset_preset_group.blp ../Gradience/data/ui/preferences_window.blp ../Gradience/data/ui/plugin_row.blp ../Gradience/data/ui/welcome_window.blp ../Gradience/data/ui/preset_row.blp ../Gradience/data/ui/builtin_preset_row.blp ../Gradience/data/ui/explore_preset_row.blp ../Gradience/data/ui/help_overlay.blp ../Gradience/data/ui/save_dialog.blp ../Gradience/data/ui/shell_prefs_window.blp ../Gradience/data/ui/shell_theming_group.blp ../Gradience/data/ui/repo_row.blp ../Gradience/data/ui/no_plugin_window.blp ../Gradience/data/ui/share_window.blp ../Gradience/data/ui/theming_empty_group.blp
error: Could not determine what kind of syntax is meant here
at ../Gradience/data/ui/error_list_row.blp line 4 column 10:
   4 |template $GradienceErrorListRow : ListBoxRow {
     |         ^

ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gradience-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
gradience-git - exit status 4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
@nikelborm update blueprint-compiler to 0.8.1

**Comment by nikelborm** [comment]
I updated blueprint compiler
It installed but with errors
![Screenshot from 2023-09-15 17-24-03](https://github.com/GradienceTeam/Gradience/assets/29357907/5f4f0983-9147-4e3a-b377-f8a79460a2b3)

I run the app with terminal
Then I open it with terminal
```
➜ gradience
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/views/welcome_window.py", line 119, in agree
    self.label_skip.set_visible(False)
    ^^^^^^^^^^^^^^^
AttributeError: 'GradienceWelcomeWindow' object has no attribute 'label_skip'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/views/welcome_window.py", line 119, in agree
    self.label_skip.set_visible(False)
    ^^^^^^^^^^^^^^^
AttributeError: 'GradienceWelcomeWindow' object has no attribute 'label_skip'
```

And in this window:

![Screenshot from 2023-09-15 17-26-12](https://github.com/GradienceTeam/Gradience/assets/29357907/fe2efc0c-3e9c-4a62-8213-fd32de8ae173)

I now cannot press "agree and continue" because it throws AttributeError (see logs above)

**Comment by nikelborm** [comment]
Reinstalled blueprint-compiler-git (it wasn't automatically updating because of version number mess)
Works kinda ok, but during installing of gradience it thrown few errors
![Screenshot from 2023-09-15 17-24-03](https://github.com/GradienceTeam/Gradience/assets/29357907/589c0309-de42-4e4e-bec2-5a92f16a3ffe)

Even so it runs. But it stuck on welcoming window, because it throws errors to the console when I try to click "Agree and Continue".
![Screenshot from 2023-09-15 17-26-12](https://github.com/GradienceTeam/Gradience/assets/29357907/77b9b551-5da5-434f-a72c-f6c0e0427420)
