### ISSUE TITLE
bug: Presets without 5 colors per palette don't apply the shell theme on GNOME 45

### ISSUE THREAD

**Issue by ThatOneCalculator** [GradienceTeam/Gradience#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When applying the shell theme, the success toast appears but the theme doesn't apply to the shell, and an error occurs in the console.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 130, in _apply_theme_thread
    output = self.apply_theme(source_object, theme_variant, preset)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 142, in apply_theme
    self._create_theme(parent, preset)
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 155, in _create_theme
    self._insert_variables()
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 176, in _insert_variables
    line = line.replace("{{" + _key + "}}", self.preset_palette[prefix + '_'][key])
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: '4'
```

### To Reproduce

1. Apply theme
2. Apply shell theme

### Expected behavior

Shell theme applies

### OS

Arch Linux 

### DE/WM version

GNOME 45.0

### Version

main branch (gradience-git from aur)

### Installation method

AUR

### Enabled system extensions (GNOME specific)

```
user-theme@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
dash-to-dock@micxgx.gmail.com
grand-theft-focus@zalckos.github.com
no-overview@fthx
appindicatorsupport@rgcjonas.gmail.com
drive-menu@gnome-shell-extensions.gcampax.github.com
dim-completed-calendar-events@marcinjahn.com
favourites-in-appgrid@harshadgavali.gitlab.org
battery-indicator-icon@Deminder
just-perfection-desktop@just-perfection
auto-move-windows@gnome-shell-extensions.gcampax.github.com
quicksettings-audio-devices-renamer@marcinjahn.com
firefox-pip@bennypowers.com
clipboard-indicator@tudmotu.com
quick-touchpad-toggle@kramo.hu
blur-my-shell@aunetx
caffeine@patapon.info
do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com
app-hider@lynith.dev
logomenu@aryan_k
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ryuuramaru** [comment]
Can confirm this issue happens on Fedora 39 Pre-Release (With GNOME 45), with Gradience installed via Flathub

**Comment by 0xMRTT** [comment]
Can you tell me which preset are you using ?

**Comment by ThatOneCalculator** [comment]
Rose Pine. It actually works fine with Pretty Purple, interestingly

**Comment by ThatOneCalculator** [comment]
The Catppuchin themes work too

**Comment by ThatOneCalculator** [comment]
Actually, it seems that almost all themes besides the Rose Pine ones work. I wonder if it's because it has an accent in its name...

**Comment by 0xMRTT** [comment]
@ThatOneCalculator no the issue is that your palette isn't complete ...

**Comment by 0xMRTT** [comment]
each color needs to have 5 sub colors, whereas rose pine only has 3 sub colors per color

**Comment by 0xMRTT** [comment]
This is why it say 4 as an error

**Comment by ThatOneCalculator** [comment]
Ref: https://github.com/GradienceTeam/Community/pull/105

**Comment by ThatOneCalculator** [comment]
I think this issue should still be open, as the bug itself isn't gone, the theme without 5 colors was fixed. Themes with less than 5 colors per category should probably autofill the remaining missing colors with the color that came before it to prevent confusion.

**Comment by Ryuuramaru** [comment]
On my end the issue occurs with any of the included themes. This is a pic after applying Pretty Purple and logging out and back in.

![image](https://github.com/GradienceTeam/Gradience/assets/39052755/2aedac2f-ce87-4b15-b851-dc128bad16b1)

This is one of the settings menu.

![image](https://github.com/GradienceTeam/Gradience/assets/39052755/49ac2be3-06be-4b9a-a2d3-6fbf5a998d41)

**Comment by 0xMRTT** [comment]
@Ryuuramaru which version of Gradience are you using ? And can you try to apply from gradience launched from CLI and send me the logs ?

**Comment by 0xMRTT** [comment]
> I think this issue should still be open, as the bug itself isn't gone, the theme without 5 colors was fixed. Themes with less than 5 colors per category should probably autofill the remaining missing colors with the color that came before it to prevent confusion.

Yeah it should :)

**Comment by 0xMRTT** [comment]
> > @Ryuuramaru which version of Gradience are you using ? And can you try to apply from gradience launched from CLI and send me the logs ?
> 
> Version 0.4.1
> 
> This is the console output: (Is this what you wanted? I couldn't find any logs)
> 
> `ryuu-fedora@fedora:~$ flatpak run --command=gradience-cli com.github.GradienceTeam.Gradience apply -n "Catppuccin Frappé" [Gradience] INFO: Preset Catppuccin Frappé applied successfully for Gtk4 applications. [Gradience] INFO: In order for changes to take full effect, you need to log out. `

Shell Theming isn't available in 0.4.1 ...

**Comment by Ryuuramaru** [comment]
Sorry!

I had assumed that since it is a Flatpak (and thus not subject to not being updated in the Fedora Repos), it would incorporate changes from 10 months ago. Looking closer at it, it is stated for a 0.8 milestone so yeah, should've really saw that before posting.

**Comment by rstanuwijaya** [comment]
Do you still have the sidebar not correctly themed after updating to 0.8? I have a similar issue as yours, but partially fixed. The left side top panel does not seem to be themed properly.  

![image](https://github.com/GradienceTeam/Gradience/assets/55012032/d67a46cd-2a60-403c-aa65-c041ccaa17fb)
