### ISSUE TITLE
bug: themes aren't being applied

### ISSUE THREAD

**Issue by M1ke-Gru** [GradienceTeam/Gradience#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I clicked on the "Apply theme" button and the theme wasn't applied to other applications. After that I closed the app, reopened it, and was met with the default light adwaita theme inside of the app, instead of the theme I applied.
This happened on Garuda Linux (Arch), tried it out on Cinnamon and Qtile, with the same result. 
Also I would like to add, that I can't install GNOME for some reason, so maybe this is not the bug in the app, but just me messing up something on my system, linked to the GTK/GNOME. 

### To Reproduce

1. Open the app
2. Change the theme inside the app
3. Click apply
4. Open other libadwaita app and see, that none of the changes are applied

### OS

Garuda Linux Qtile Edition

### DE/WM version

Qtile

### Version

Literally installed it today

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

Lxappearance

### Additional context

Again, this might be just the problem with me messing something else up, because GNOME and Budgie won't start. Although Cinnamon runs perfectly fine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment]
Could you try to run it from the cli and send us the output ?

**Comment by M1ke-Gru** [comment]
gradience

(process:18362): Gtk-WARNING **: 23:17:24.165: Theme parser error: gtk-dark.css:7570:21-28: Expected a valid color.

(process:18362): Gtk-WARNING **: 23:17:24.165: Theme parser error: gtk-dark.css:7575:21-28: Expected a valid color.

(process:18362): Gtk-WARNING **: 23:17:24.165: Theme parser error: gtk-dark.css:7745:21-28: Expected a valid color.

(process:18362): Gtk-WARNING **: 23:17:24.165: Theme parser error: gtk-dark.css:7751:21-28: Expected a valid color.

(process:18362): Adwaita-WARNING **: 23:17:24.186: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
[Gradience] WARNING: Custom preset not found. Fallback to Adwaita

// Here I tried applying adwaita dark

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/main.py", line 623, in apply_color_scheme
    PresetUtils().apply_preset("gtk4", self.preset)
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/preset_utils.py", line 258, in apply_preset
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/mike/.config/gtk-4.0/gtk.css'

**Comment by MatrixFurry** [comment]
Not sure if your issue is the same as mine was, but try making sure Gradience has permission to read and write xdg-config/gtk-4.0 and xdg-config/gtk-3.0.

**Comment by zefr0x** [comment]
The `:ro` option is used in the flatpak. Is should be `:rw` to be able to read and write, or may be `:create` to create a directory if it doesn't exist.

**Comment by M1ke-Gru** [comment]
@MatrixFurry where is xdg-config? I am a little bit of a noob and I can't find it. Simple search in home folder showed me nothing, and it took absurdly long to find it on my filesystem.

**Comment by M1ke-Gru** [comment]
@daudix-UFO it looks like it is missing

**Comment by daudix-UFO** [comment]
The whole .config or gtk-3.0 and gtk-4.0 ?

**Comment by MatrixFurry** [comment]
@M1ke-Gru:
> @MatrixFurry where is xdg-config? I am a little bit of a noob and I can't find it. Simple search in home folder showed me nothing, and it took absurdly long to find it on my filesystem.

Try doing `echo "$XDG_CONFIG"`. If it is blank, your config directory should be at `~/.config/`. If it is set, check that directory. Make sure you're showing hidden files with the `-a` flag for `ls` or `exa` :). If you're using a GUI, make sure you have hidden files enabled there. If the directories `gtk-3.0` or `gtk-4.0` are missing inside your configuration directory, create them.

**Comment by medmedin2014** [comment]
I'm using EasyEffects on Plasma desktop 5.27.9, and can't bear that ugly Adwaita theme.

So I installed Gradience via AUR, and applying Dark Breeze changes the current running Gradience instance, but if I reopen it again it reset to Adwaita, and EeasyEffects always use Adwaita theme.

![Screenshot_20231125_201033](https://github.com/GradienceTeam/Gradience/assets/7027319/4342e370-7666-4e8d-968e-a8ba618e8473)

**Comment by a-morally** [comment]
Had the same problem. Gradience did have permissions to xdg-config/gtk-3.0 and xdg-config/gtk-4.0 but the directories were not created. So, check if those dirs exist.
