### ISSUE TITLE
bug: GradiencePluginRow (Plugins will not work)

### ISSUE THREAD

**Issue by keilmillerjr** [GradienceTeam/Gradience#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!Errors when launching gradience.
```
❯ gradience

(process:36477): Adwaita-WARNING **: 14:37:06.066: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(gradience:36477): Gtk-CRITICAL **: 14:37:06.164: Unable to retrieve child object 'settings-button' from class template for type 'GradiencePluginRow' while building a 'GradiencePluginRow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 170, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 193, in init_template
    raise RuntimeError(
RuntimeError: Handler 'on_settings_plugin_clicked' was declared with @Gtk.Template.Callback but was not present in template

(gradience:36477): Gtk-CRITICAL **: 14:37:06.164: Unable to retrieve child object 'settings-button' from class template for type 'GradiencePluginRow' while building a 'GradiencePluginRow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 170, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 193, in init_template
    raise RuntimeError(
RuntimeError: Handler 'on_settings_plugin_clicked' was declared with @Gtk.Template.Callback but was not present in template

(gradience:36477): Gtk-CRITICAL **: 14:37:06.165: Unable to retrieve child object 'settings-button' from class template for type 'GradiencePluginRow' while building a 'GradiencePluginRow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 170, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 193, in init_template
    raise RuntimeError(
RuntimeError: Handler 'on_settings_plugin_clicked' was declared with @Gtk.Template.Callback but was not present in template
```

Error when toggling any item under Advanced/Plugins.
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/widgets/plugin_row.py", line 95, in on_switch_toggled
    if self.switch.get_active():
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_active'
```

### To Reproduce

1. Install the following arch/aur packages:
  * gradience-git
  * adw-gtk-theme
  * libadwaita-without-adwaita-git
  * firefox
  * firefox-gnome-theme-git
2. `$ gradience`
3. Click on the Advanced tab.
4. Clock on any one of three toggle switches within the Plugin section.

### Expected behavior

Not an error. I want to be able to apply gradience theme to Firefox.

### OS

Arch

### DE/WM version

Hyprland

### Version

0.8.0-beta2

### Installation method

AUR

### Enabled system extensions (GNOME specific)

I do not use the gnome shell.

### Additional context

See related issue: https://github.com/GradienceTeam/Gradience/issues/858

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikelborm** [comment]
@keilmillerjr What version of gnome do you use?
I have similar error to yours which appeared only recently and may be caused by newest release of Gnome 46
https://github.com/GradienceTeam/Gradience/issues/871#issuecomment-2025620396
