### ISSUE TITLE
feat: Support for GNOME Shell 46

### ISSUE THREAD

**Issue by arm32x** [GradienceTeam/Gradience#871]
### Feature description

The GNOME Shell theming support included in the nightly version of Gradience does not work with GNOME Shell 46. It would be nice if this was supported, especially considering that GNOME Shell 46 is now in the Arch package repos.

### Additional Context

I'm using version `0.8.0.beta1.r199.gee5bc573-1` of the `gradience-git` package from the AUR. This is the stack trace that occurs when I press the Apply button:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
                                                   ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 59, in __init__
    self._detect_shell_version()
  File "/usr/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 278, in _detect_shell_version
    raise UnsupportedShellVersion(
gradience.backend.exceptions.UnsupportedShellVersion: GNOME Shell version 46 is not supported. (Supported versions: 42, 43, 44, 45)
```

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by nikelborm** [comment]
Doesn't work for me too, but with different error on gnome 46
```
(gradience:341594): Gtk-CRITICAL **: 19:18:26.276: Unable to retrieve child object 'settings-button' from class template for type 'GradiencePluginRow' while building a 'GradiencePluginRow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 170, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 193, in init_template
    raise RuntimeError(
RuntimeError: Handler 'on_settings_plugin_clicked' was declared with @Gtk.Template.Callback but was not present in template

(gradience:341594): Gtk-CRITICAL **: 19:18:26.277: Unable to retrieve child object 'settings-button' from class template for type 'GradiencePluginRow' while building a 'GradiencePluginRow'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 170, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/_gtktemplate.py", line 193, in init_template
    raise RuntimeError(
RuntimeError: Handler 'on_settings_plugin_clicked' was declared with @Gtk.Template.Callback but was not present in template
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gradience/frontend/main.py", line 117, in do_activate
    self.setup_plugins()
  File "/usr/lib/python3.11/site-packages/gradience/frontend/main.py", line 629, in setup_plugins
    self.plugins_group = self.plugins_list.to_group()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gradience/frontend/views/plugins_list.py", line 98, in to_group
    row = GradiencePluginRow(pluginInfo.plugin_object, preset, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gradience/frontend/widgets/plugin_row.py", line 60, in __init__
    self.switch.set_active(True)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_active'
```

**Comment by drannex42** [comment]
Throwing my report in the ring here. Gnome 46. Running off Nightly.

```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gradience/frontend/widgets/shell_theming_group.py", line 113, in on_apply_button_clicked
    user_themes_available = is_shell_ext_installed(ShellTheme().THEME_EXT_NAME)
                                                   ^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 59, in __init__
    self._detect_shell_version()
  File "/app/lib/python3.11/site-packages/gradience/backend/theming/shell.py", line 278, in _detect_shell_version
    raise UnsupportedShellVersion(
gradience.backend.exceptions.UnsupportedShellVersion: GNOME Shell version 46 is not supported. (Supported versions: 42, 43, 44, 45)
```
