### ISSUE TITLE
bug:  Gradience didn't open in Arch Linux

### ISSUE THREAD

**Issue by gustavojoaquin** [GradienceTeam/Gradience#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, i installed Gradience in Arch Linux but it didn't open, i just have this error:
```
gradience
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yapsy/PluginManager.py", line 132, in <module>
    import importlib.abc.Loader as imp
ModuleNotFoundError: No module named 'importlib.abc.Loader'; 'importlib.abc' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gradience", line 70, in <module>
    from gradience.frontend import main
  File "/usr/lib/python3.12/site-packages/gradience/frontend/main.py", line 37, in <module>
    from gradience.frontend.views.plugins_list import GradiencePluginsList
  File "/usr/lib/python3.12/site-packages/gradience/frontend/views/plugins_list.py", line 22, in <module>
    from yapsy.PluginManager import PluginManager
  File "/usr/lib/python3.12/site-packages/yapsy/PluginManager.py", line 134, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

### To Reproduce

`paru -S gradience` or `paru -S gradience-git`
`$ gradience`

### Expected behavior

I expect Gradience open

### Screenshots

![image](https://github.com/GradienceTeam/Gradience/assets/93671143/09150688-96c4-485b-a01d-926d6cad85c7)

### OS

Arch Linux

### DE/WM version

Swayfx

### Version

latest

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Almamu** [comment]
This is related to #890, that workaround seems to do the job for now in Arch.

**Comment by JarneDel** [comment]
I have a similar behaviour, but with the yapsy package
 gradience
Traceback (most recent call last):
  File "/usr/bin/gradience", line 70, in <module>
    from gradience.frontend import main
  File "/usr/lib/python3.12/site-packages/gradience/frontend/main.py", line 37, in <module>
    from gradience.frontend.views.plugins_list import GradiencePluginsList
  File "/usr/lib/python3.12/site-packages/gradience/frontend/views/plugins_list.py", line 22, in <module>
    from yapsy.PluginManager import PluginManager
ModuleNotFoundError: No module named 'yapsy'

**Comment by keilmillerjr** [comment]
I can confirm that the aur package [gradience-git](https://aur.archlinux.org/packages/gradience-git) is broken. [python-yapsy](https://aur.archlinux.org/packages/python-yapsy) is no longer available, so I removed the package and dependencies, and reinstalled using the alternative [python-yapsy-git](https://aur.archlinux.org/packages/python-yapsy-git). Here is my log.

```
Traceback (most recent call last):
  File "/usr/bin/gradience", line 70, in <module>
    from gradience.frontend import main
  File "/usr/lib/python3.12/site-packages/gradience/frontend/main.py", line 24, in <module>
    from material_color_utilities_python import hexFromArgb
ModuleNotFoundError: No module named 'material_color_utilities_python'
```
